"""Add unique constraint to payments

Revision ID: 4ecea7999617
Revises: fedfa99030e7
Create Date: 2026-09-29 10:43:08.617805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ecea7999617'
down_revision: Union[str, Sequence[str], None] = 'fedfa99030e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_payment_booking', 'payments', ['booking_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_booking', 'payments', type_='unique')
    # ### end Alembic commands ###
